server.port: 8080
spring.rabbitmq.broker-url: http://localhost:15672/#/
spring.rabbitmq.username: guest
spring.rabbitmq.password: guest
spring.cloud.stream.bindings.output.destination: mydestination
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: mydestination

